/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author PC17
 */
public class ViewOperaciones extends javax.swing.JPanel {

    /**
     * Creates new form ViewOperaciones
     */
    public ViewOperaciones() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jl_num1 = new javax.swing.JLabel();
        jl_num2 = new javax.swing.JLabel();
        jtf_num1 = new javax.swing.JTextField();
        jtf_num2 = new javax.swing.JTextField();
        jl_resultado = new javax.swing.JLabel();
        jtf_resultado = new javax.swing.JTextField();
        jbtn_mas = new javax.swing.JButton();
        jbtn_menos = new javax.swing.JButton();
        jbtn_por = new javax.swing.JButton();
        jbtn_entre = new javax.swing.JButton();

        jl_num1.setText("Número 1");

        jl_num2.setText("Numero 2");

        jtf_num1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_num1ActionPerformed(evt);
            }
        });

        jl_resultado.setText("Resultado");

        jbtn_mas.setText("+");
        jbtn_mas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_masActionPerformed(evt);
            }
        });

        jbtn_menos.setText("-");

        jbtn_por.setText("*");

        jbtn_entre.setText("/");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jl_num1)
                            .addComponent(jl_num2)
                            .addComponent(jl_resultado))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtf_num1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtf_resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtf_num2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jbtn_mas)
                        .addGap(9, 9, 9)
                        .addComponent(jbtn_menos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtn_por)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbtn_entre)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_num1)
                    .addComponent(jtf_num1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_num2)
                    .addComponent(jtf_num2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_resultado)
                    .addComponent(jtf_resultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn_mas)
                    .addComponent(jbtn_menos)
                    .addComponent(jbtn_por)
                    .addComponent(jbtn_entre))
                .addContainerGap(37, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jtf_num1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_num1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_num1ActionPerformed

    private void jbtn_masActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_masActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtn_masActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jbtn_entre;
    public javax.swing.JButton jbtn_mas;
    public javax.swing.JButton jbtn_menos;
    public javax.swing.JButton jbtn_por;
    private javax.swing.JLabel jl_num1;
    private javax.swing.JLabel jl_num2;
    private javax.swing.JLabel jl_resultado;
    public javax.swing.JTextField jtf_num1;
    public javax.swing.JTextField jtf_num2;
    public javax.swing.JTextField jtf_resultado;
    // End of variables declaration//GEN-END:variables
}
